import type { DeveloperSubskillSpec } from "../types";

export const DEVELOPER_SUBSKILLS: DeveloperSubskillSpec[] = [
  {
    id: "contract-architecture",
    title: "Contract Architecture",
    summary: "Design contract modules, storage layout, access control, and upgrade boundaries before code is written.",
    risk: "high",
    approvalRequired: true,
    useWhen: [
      "system design",
      "module boundaries",
      "storage layout",
      "access control",
      "upgradeability",
      "contract architecture",
    ],
    workflow: [
      "Clarify the product goal, trust model, and onchain constraints.",
      "Split the system into modules, interfaces, and storage responsibilities.",
      "Identify upgrade, ownership, and permission decisions explicitly.",
      "Present the architecture and ask for approval before implementation.",
    ],
    deliverables: ["module map", "storage plan", "access-control plan", "risk notes"],
    examples: [
      "Design the architecture for a multi-role marketplace contract",
      "Propose the storage and access model for a staking protocol",
    ],
  },
  {
    id: "solidity-authoring",
    title: "Solidity Authoring",
    summary: "Write or refactor Solidity contracts with clear structure, comments, and implementation-ready details.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["write solidity", "implement contract", "refactor contract", "contract code", "solidity"],
    workflow: [
      "Capture the contract goal, inputs, outputs, and invariants.",
      "Draft the contract shape, custom errors, events, and modifiers.",
      "Show the implementation plan and wait for confirmation.",
      "Write the contract in a way that is easy to test and review.",
    ],
    deliverables: ["contract draft", "event and error plan", "implementation notes", "test hooks"],
    examples: [
      "Write a Solidity escrow contract with refund and dispute paths",
      "Refactor this token contract to use custom errors and events",
    ],
  },
  {
    id: "interface-abi-design",
    title: "Interface and ABI Design",
    summary: "Define interfaces, events, errors, and typed bindings so downstream tooling can integrate cleanly.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["abi", "interface", "events", "errors", "typed bindings", "contract surface"],
    workflow: [
      "List the methods, events, and revert paths that must be exposed.",
      "Normalize naming so frontend and backend tooling can use the same surface.",
      "Show the ABI/interface plan and ask if the shape is correct.",
      "Generate the interface or binding skeleton after confirmation.",
    ],
    deliverables: ["interface spec", "event list", "error list", "typed binding notes"],
    examples: [
      "Design the ABI for a vault with deposit and withdraw flows",
      "Create a typed interface for the contract methods this dapp needs",
    ],
  },
  {
    id: "protocol-integration-planning",
    title: "Protocol Integration Planning",
    summary: "Plan read/write flows, approvals, and call order for integrating a protocol or contract surface.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["integration", "protocol flow", "call sequence", "approval flow", "contract interaction plan"],
    workflow: [
      "Identify the integration target, wallet flow, and data dependencies.",
      "Sequence the reads, approvals, writes, and fallback paths.",
      "Call out error handling, retries, and user-facing states.",
      "Present the full integration plan before implementation.",
    ],
    deliverables: ["call sequence", "approval flow", "error paths", "integration checklist"],
    examples: [
      "Plan the integration flow for a staking dashboard",
      "Map the call sequence for a lending protocol deposit flow",
    ],
  },
  {
    id: "frontend-dapp-integration",
    title: "Frontend Dapp Integration",
    summary: "Connect UI components to contract actions, state, and transaction previews.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["frontend", "dapp", "ui integration", "wallet connect", "view state", "transaction preview"],
    workflow: [
      "Map the user journey and the contract state the UI needs.",
      "Choose the minimal component tree and data flow.",
      "Show the integration plan, including files and props.",
      "Implement the UI wiring after the user confirms the direction.",
    ],
    deliverables: ["component map", "data flow", "state plan", "integration notes"],
    examples: [
      "Integrate a Next.js UI with contract reads and writes",
      "Build the frontend layer for a mint flow with transaction preview",
    ],
  },
  {
    id: "wallet-and-transaction-ui",
    title: "Wallet and Transaction UI",
    summary: "Design wallet connection, transaction preview, status, and history screens that feel reliable.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["wallet ui", "transaction ui", "preview", "status screen", "history", "connection flow"],
    workflow: [
      "Identify the wallet states, transaction states, and error states.",
      "Define the screen sequence and what each state shows.",
      "Present the UI plan and ask for changes before implementation.",
      "Build the smallest working state machine and verify the transitions.",
    ],
    deliverables: ["screen flow", "state machine", "copy plan", "error-state checklist"],
    examples: [
      "Design a transaction preview modal with gas and risk details",
      "Create wallet status and history components for a dapp",
    ],
  },
  {
    id: "framework-integration",
    title: "Framework Integration",
    summary: "Wire Pharos development patterns into Next.js, wagmi, viem, ethers, Foundry, Hardhat, or Remix.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["next.js", "wagmi", "viem", "ethers", "foundry", "hardhat", "remix", "framework setup"],
    workflow: [
      "Detect the framework and current app shape.",
      "Map the minimal integration changes and config updates.",
      "Show the plan and proceed once it looks right.",
      "Verify the integration with the smallest useful build or config check.",
    ],
    deliverables: ["integration checklist", "config changes", "setup steps", "verification command"],
    examples: [
      "Add wagmi and viem wiring to this Next.js app",
      "Prepare a Foundry project for contract development on Pharos",
    ],
  },
  {
    id: "testing-strategy",
    title: "Testing Strategy",
    summary: "Choose the right test mix, fixtures, and coverage focus before writing tests.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["test strategy", "coverage", "fixtures", "edge cases", "test plan"],
    workflow: [
      "Identify the contract, UI, or integration risks that matter most.",
      "Choose unit, integration, and regression coverage appropriately.",
      "Present the testing plan with explicit assumptions.",
      "Wait for confirmation before generating tests or fixtures.",
    ],
    deliverables: ["test matrix", "fixture plan", "coverage goals", "regression checklist"],
    examples: [
      "Design the test strategy for a token sale contract",
      "Plan coverage for a multi-step dapp transaction flow",
    ],
  },
  {
    id: "test-generation",
    title: "Test Generation",
    summary: "Write unit, integration, or end-to-end tests from the chosen strategy.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["write tests", "generate tests", "fixtures", "mock data", "test files"],
    workflow: [
      "Use the approved test strategy and identify concrete cases.",
      "Draft the tests with readable setup and assertions.",
      "Show the test plan and ask if the cases are correct.",
      "Generate the tests and verify they fail or pass as intended.",
    ],
    deliverables: ["test files", "fixtures", "assertions", "coverage notes"],
    examples: [
      "Generate tests for the withdraw path and failure branches",
      "Create UI tests for transaction preview states",
    ],
  },
  {
    id: "contract-review",
    title: "Contract Review",
    summary: "Review Solidity code for correctness, security, gas, and design issues.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["review contract", "audit", "security review", "solidity review", "gas review"],
    workflow: [
      "Read the contract surface and identify the trust boundaries.",
      "Look for access-control issues, invariants, and unsafe assumptions.",
      "Summarize findings with severity and evidence.",
      "Present the review and ask whether to patch the issues.",
    ],
    deliverables: ["findings list", "severity assessment", "evidence notes", "patch priorities"],
    examples: [
      "Review this vault contract for access-control mistakes",
      "Audit this mint function for reentrancy and supply bugs",
    ],
  },
  {
    id: "bug-finding-and-debugging",
    title: "Bug Finding and Debugging",
    summary: "Trace failures in compile, runtime, test, or UI behavior and propose focused fixes.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["bug", "debug", "error", "failing build", "failing test", "runtime issue"],
    workflow: [
      "Reproduce or reason about the failure from the error output.",
      "Isolate the root cause and the smallest safe fix.",
      "Show the fix plan and ask for approval before editing.",
      "Patch the issue and verify the failure is gone.",
    ],
    deliverables: ["root cause", "fix plan", "patch notes", "verification result"],
    examples: [
      "Debug this failing contract test and explain the root cause",
      "Find why the frontend transaction state never updates",
    ],
  },
  {
    id: "deployment-and-verification",
    title: "Deployment and Verification",
    summary: "Prepare deploy scripts, env variables, explorer verification, and post-deploy checks.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["deploy", "verification", "explorer", "release", "publish contract"],
    workflow: [
      "Confirm the deployment target, network, and required config.",
      "Draft the deploy and verification steps explicitly.",
      "Present the plan and wait for approval before any deploy-side change.",
      "Verify the deployed artifact and capture the outcome.",
    ],
    deliverables: ["deployment steps", "verification checklist", "env var list", "post-deploy checks"],
    examples: [
      "Prepare the deploy and verification flow for this contract",
      "Write the release checklist for a Pharos contract rollout",
    ],
  },
  {
    id: "migration-and-backward-compatibility",
    title: "Migration and Backward Compatibility",
    summary: "Plan safe migrations, data moves, and compatibility guardrails for upgrades or rewrites.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["migration", "backward compatibility", "upgrade path", "data move", "breaking change"],
    workflow: [
      "Identify the old state, new state, and compatibility boundary.",
      "Map the migration path, fallbacks, and rollback assumptions.",
      "Present the migration plan and ask for confirmation before changes.",
      "Implement the smallest safe migration step after approval.",
    ],
    deliverables: ["migration plan", "compatibility notes", "rollback plan", "verification checklist"],
    examples: [
      "Plan a contract upgrade migration without breaking existing users",
      "Design the compatibility layer for a protocol rewrite",
    ],
  },
  {
    id: "refactoring-and-code-health",
    title: "Refactoring and Code Health",
    summary: "Improve structure, readability, naming, and separation of concerns without changing behavior.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["refactor", "code health", "cleanup", "simplify", "remove duplication"],
    workflow: [
      "Identify the code smells or maintenance costs.",
      "Propose the refactor scope and behavior guarantees.",
      "Show the plan and ask if the direction is correct.",
      "Refactor with tests or checks that preserve behavior.",
    ],
    deliverables: ["refactor plan", "behavior guarantees", "cleanup notes", "verification result"],
    examples: [
      "Refactor this hook to separate data fetching from UI state",
      "Improve the code health of this contract module without changing behavior",
    ],
  },
  {
    id: "dependency-upgrade-management",
    title: "Dependency Upgrade Management",
    summary: "Upgrade packages or toolchains with version-aware compatibility checks and rollback planning.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["dependency upgrade", "package update", "toolchain update", "version bump"],
    workflow: [
      "List the packages or toolchain components that need changing.",
      "Check compatibility risk and any required code changes.",
      "Present the upgrade plan and ask for confirmation.",
      "Apply the upgrade and verify the build or tests.",
    ],
    deliverables: ["upgrade plan", "compatibility notes", "version list", "verification result"],
    examples: [
      "Upgrade the dependencies in this repo and keep the change minimal",
      "Plan the toolchain bump from one TypeScript version to another",
    ],
  },
  {
    id: "performance-optimization",
    title: "Performance Optimization",
    summary: "Find and reduce runtime, render, bundle, or gas-adjacent inefficiencies in code paths.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["performance", "optimize", "slow", "bottleneck", "bundle size", "latency"],
    workflow: [
      "Locate the performance bottleneck or suspected hot path.",
      "Propose a measurable optimization strategy.",
      "Show the plan and ask for approval before changes.",
      "Implement the smallest change that improves the metric and verify it.",
    ],
    deliverables: ["bottleneck analysis", "optimization plan", "metric target", "verification result"],
    examples: [
      "Optimize this React rendering path",
      "Reduce the build size and startup cost of this dapp",
    ],
  },
  {
    id: "accessibility-review",
    title: "Accessibility Review",
    summary: "Review UI behavior for keyboard support, semantics, contrast, and screen-reader friendliness.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["accessibility", "a11y", "keyboard", "screen reader", "contrast", "semantics"],
    workflow: [
      "Inspect the UI flow for accessibility-sensitive interactions.",
      "List the issues by severity and user impact.",
      "Present the accessibility plan and ask if the fixes are correct.",
      "Patch the issues and verify the interaction paths again.",
    ],
    deliverables: ["accessibility findings", "severity list", "fix plan", "verification notes"],
    examples: [
      "Review this transaction modal for accessibility issues",
      "Check whether this wallet flow is keyboard-friendly",
    ],
  },
  {
    id: "release-notes-and-changelog",
    title: "Release Notes and Changelog",
    summary: "Turn a set of code changes into clear release notes, changelog entries, or PR summaries.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["release notes", "changelog", "release summary", "pr summary", "shipping notes"],
    workflow: [
      "Summarize the user-facing changes and risks.",
      "Draft release notes or changelog entries in clear language.",
      "Show the outline and proceed once it looks right.",
      "Keep the notes tied to the actual diff and not marketing fluff.",
    ],
    deliverables: ["release note draft", "changelog entry", "risk notes", "summary bullets"],
    examples: [
      "Write the changelog entry for this dapp release",
      "Summarize the key changes for a Pharos package update",
    ],
  },
  {
    id: "code-scaffolding-and-generation",
    title: "Code Scaffolding and Generation",
    summary: "Generate starter files, boilerplate, or project scaffolds for a new developer workflow.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["scaffold", "starter", "boilerplate", "generate files", "template"],
    workflow: [
      "Identify the target structure and minimum usable files.",
      "Draft the scaffold and explain the generated pieces.",
      "Show the plan and proceed once it looks right.",
      "Keep the scaffold minimal and directly useful.",
    ],
    deliverables: ["file scaffold", "starter layout", "generation notes", "follow-up suggestions"],
    examples: [
      "Scaffold a contract test folder and helper layout",
      "Generate a starter Next.js integration structure for this dapp",
    ],
  },
  {
    id: "state-management-integration",
    title: "State Management Integration",
    summary: "Wire app state into query, store, cache, or client-side state tools without creating drift.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["state management", "zustand", "redux", "query client", "cache", "store"],
    workflow: [
      "Identify the state ownership model and update flow.",
      "Choose the minimal state tool or pattern that fits the app.",
      "Show the plan and ask for approval before implementation.",
      "Wire the state and verify the update path.",
    ],
    deliverables: ["state flow", "store design", "update plan", "verification notes"],
    examples: [
      "Integrate Zustand into this dashboard",
      "Plan how React Query should handle cached contract reads in the UI",
    ],
  },
  {
    id: "monorepo-workspace-management",
    title: "Monorepo and Workspace Management",
    summary: "Handle workspace boundaries, package scripts, and shared tooling in monorepos.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["monorepo", "workspace", "turborepo", "pnpm workspace", "shared package"],
    workflow: [
      "Map the workspace structure and package boundaries.",
      "Identify the minimum workspace changes required.",
      "Present the plan and ask for confirmation.",
      "Apply the workspace changes and verify the affected packages.",
    ],
    deliverables: ["workspace map", "package boundary notes", "script changes", "verification result"],
    examples: [
      "Organize this repo as a monorepo with shared packages",
      "Fix the workspace scripts so the app and contracts build together",
    ],
  },
  {
    id: "localization-and-copy",
    title: "Localization and Copy",
    summary: "Adjust product copy, labels, and localization structure for clearer user-facing text.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["localization", "i18n", "translation", "copy", "microcopy", "labels"],
    workflow: [
      "Identify the user-facing strings and target locales or tone.",
      "Draft improved copy or localization structure.",
      "Show the plan and proceed once it looks right.",
      "Keep the wording aligned with the product context and flow.",
    ],
    deliverables: ["copy draft", "localization notes", "string list", "tone guidance"],
    examples: [
      "Improve the copy for this wallet connect flow",
      "Prepare the localization structure for a future multi-language release",
    ],
  },
  {
    id: "repo-automation-and-tooling",
    title: "Repo Automation and Tooling",
    summary: "Design scripts, automation flows, task runners, and local developer tooling.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["automation", "scripts", "task runner", "makefile", "precommit", "tooling"],
    workflow: [
      "Identify the repetitive task or workflow that should be automated.",
      "Choose the lightest useful automation surface.",
      "Show the script or tooling plan and proceed once it looks right.",
      "Keep the automation easy to understand and easy to undo.",
    ],
    deliverables: ["automation plan", "script notes", "tooling checklist", "maintenance notes"],
    examples: [
      "Set up scripts to run lint, test, and build in one command",
      "Design the local tooling workflow for this repo",
    ],
  },
  {
    id: "code-review-templates-and-checklists",
    title: "Code Review Templates and Checklists",
    summary: "Create review templates, PR checklists, and evaluation rubrics for better code review hygiene.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["code review template", "pr checklist", "review rubric", "review checklist", "review notes"],
    workflow: [
      "Identify the review audience and review goals.",
      "Draft a concise checklist or template with concrete prompts.",
      "Show the outline and proceed once it looks right.",
      "Keep the template short enough that people will actually use it.",
    ],
    deliverables: ["review template", "checklist", "rubric", "usage notes"],
    examples: [
      "Write a PR checklist for this Pharos repo",
      "Create a code review template for contract changes",
    ],
  },
  {
    id: "nextjs-app-router-and-server-actions",
    title: "Next.js App Router and Server Actions",
    summary: "Handle Next.js App Router, route handlers, server actions, and RSC patterns.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["next.js app router", "server actions", "route handlers", "rsc", "nextjs"],
    workflow: [
      "Map the route, server, and client boundaries.",
      "Choose the minimal App Router pattern that fits the feature.",
      "Show the plan and proceed once it looks right.",
      "Verify the app structure or runtime behavior after the change.",
    ],
    deliverables: ["route plan", "component boundary notes", "server action notes", "verification result"],
    examples: [
      "Add a Next.js App Router pattern for this dapp flow",
      "Design a server action flow for a contract helper UI",
    ],
  },
  {
    id: "react-ui-patterns-and-hooks",
    title: "React UI Patterns and Hooks",
    summary: "Improve React hooks, component boundaries, and client-side UI patterns.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["react hooks", "component pattern", "context", "state hook", "ui patterns"],
    workflow: [
      "Identify the state and rendering pattern that needs support.",
      "Suggest the smallest React pattern that fits the feature.",
      "Show the plan and proceed once it looks right.",
      "Keep the component shape simple enough to maintain.",
    ],
    deliverables: ["hook plan", "component notes", "rendering notes", "follow-up suggestions"],
    examples: [
      "Refine this React hook and component boundary",
      "Design a cleaner state pattern for this wallet flow UI",
    ],
  },
  {
    id: "wagmi-viem-dapp-workflow",
    title: "Wagmi and Viem Dapp Workflow",
    summary: "Handle wallet connection, contract reads, writes, and dapp integration patterns using Wagmi and Viem.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["wagmi", "viem", "wallet connect", "contract read", "contract write", "dapp workflow"],
    workflow: [
      "Map the contract and wallet interactions the UI needs.",
      "Choose the minimal Wagmi and Viem integration pattern.",
      "Show the plan and proceed once it looks right.",
      "Verify the configuration and flow with a small smoke check.",
    ],
    deliverables: ["integration plan", "hook notes", "config notes", "smoke-check suggestion"],
    examples: [
      "Wire Wagmi and Viem into this dapp flow",
      "Plan the contract read and write helpers for a wallet-connected UI",
    ],
  },
  {
    id: "foundry-hardhat-contract-workflow",
    title: "Foundry and Hardhat Contract Workflow",
    summary: "Set up Solidity development workflows for Foundry or Hardhat, including tests, scripts, and local runs.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["foundry", "hardhat", "forge", "anvil", "solidity workflow", "contract workflow"],
    workflow: [
      "Identify the contract task and the local dev stack.",
      "Choose the smallest Foundry or Hardhat workflow that fits the request.",
      "Show the plan and proceed once it looks right.",
      "Verify the workflow with the smallest useful command or file change.",
    ],
    deliverables: ["workflow plan", "script notes", "test notes", "verification command"],
    examples: [
      "Set up a Foundry workflow for this contract repo",
      "Create the Hardhat contract workflow for tests and scripts",
    ],
  },
  {
    id: "remix-contract-workflow",
    title: "Remix Contract Workflow",
    summary: "Set up Remix-based contract development, testing, and quick iteration flows.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["remix", "browser solidity", "quick contract iteration", "remix workflow"],
    workflow: [
      "Identify the contract task and Remix-specific constraints.",
      "Choose the smallest workflow or file structure that fits the task.",
      "Show the plan and proceed once it looks right.",
      "Verify the result with a simple local or browser-based check.",
    ],
    deliverables: ["Remix plan", "file notes", "workflow steps", "verification suggestion"],
    examples: [
      "Set up a Remix workflow for rapid Solidity iteration",
      "Plan a contract test flow using Remix in the browser",
    ],
  },
  {
    id: "tailwind-shadcn-ui-workflow",
    title: "Tailwind and shadcn/ui Workflow",
    summary: "Design and implement polished UI flows using Tailwind and shadcn/ui patterns.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["tailwind", "shadcn", "ui workflow", "design system", "component styles"],
    workflow: [
      "Identify the UI surface and the design constraints.",
      "Choose the smallest Tailwind and shadcn/ui pattern that fits the task.",
      "Show the plan and proceed once it looks right.",
      "Verify the component structure and styling outcome.",
    ],
    deliverables: ["UI plan", "component notes", "style notes", "verification hint"],
    examples: [
      "Build a Tailwind and shadcn/ui flow for a wallet preview modal",
      "Design the UI component patterns for this Pharos dashboard",
    ],
  },
  {
    id: "deployment-for-testnet-and-mainnet",
    title: "Deployment for Testnet and Mainnet",
    summary: "Plan and validate contract deployments across testnet and mainnet with environment-aware safeguards.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["testnet", "mainnet", "deployment", "release", "deploy flow", "network-specific deploy"],
    workflow: [
      "Identify the target network, deployment artifact, and release assumptions.",
      "Separate testnet validation from mainnet release steps.",
      "Show the deployment plan and ask for explicit approval.",
      "Use the smallest safe verification step after deployment.",
    ],
    deliverables: ["network plan", "deployment steps", "release checklist", "verification checklist"],
    examples: [
      "Plan the testnet deployment and mainnet release flow for this contract",
      "Prepare a safe deployment checklist for both Pharos networks",
    ],
  },
  {
    id: "contract-testing-for-testnet-and-mainnet",
    title: "Contract Testing for Testnet and Mainnet",
    summary: "Design contract test coverage and environment-aware checks for both network contexts.",
    risk: "medium",
    approvalRequired: true,
    useWhen: ["contract testing", "testnet tests", "mainnet tests", "network-specific testing", "environment-aware tests"],
    workflow: [
      "Separate local unit coverage from network-aware checks.",
      "Plan how testnet and mainnet constraints differ.",
      "Show the test plan and ask for approval before generating tests.",
      "Write tests or checks that make the network boundary explicit.",
    ],
    deliverables: ["test matrix", "network coverage plan", "fixture notes", "verification command"],
    examples: [
      "Design contract tests that cover both testnet and mainnet assumptions",
      "Plan the network-specific test checks for this deployment flow",
    ],
  },
  {
    id: "repo-onboarding",
    title: "Repo Onboarding",
    summary: "Map the codebase, entrypoints, scripts, and conventions so future work starts from the right place.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["onboard", "map repo", "entrypoints", "project layout", "where is the code"],
    workflow: [
      "Identify the app entrypoints, scripts, and top-level modules.",
      "Summarize the relevant folders and conventions.",
      "Return a concise map that helps the next task start quickly.",
      "Note any unknowns or missing context explicitly.",
    ],
    deliverables: ["repo map", "entrypoint list", "script list", "open questions"],
    examples: [
      "Map this repo so I can start the dapp integration work",
      "Show the important files and commands in this project",
    ],
  },
  {
    id: "docs-and-example-generation",
    title: "Docs and Example Generation",
    summary: "Write clear docs, usage instructions, and examples for developers and agents.",
    risk: "low",
    approvalRequired: false,
    useWhen: ["docs", "readme", "examples", "usage instructions", "agent prompt", "guides"],
    workflow: [
      "Identify the audience and the exact usage scenario.",
      "Draft concise examples and verification steps.",
      "Show the outline and proceed once it looks right.",
      "Keep the docs aligned with the actual implementation.",
    ],
    deliverables: ["docs draft", "examples", "usage steps", "notes for maintainers"],
    examples: [
      "Write developer docs for this contract helper",
      "Generate example prompts for the Pharos skill suite",
    ],
  },
  {
    id: "ci-and-build-troubleshooting",
    title: "CI and Build Troubleshooting",
    summary: "Diagnose failing builds, type errors, lint jobs, and CI regressions with a narrow fix path.",
    risk: "high",
    approvalRequired: true,
    useWhen: ["ci", "build failure", "lint failure", "type error", "pipeline", "broken test job"],
    workflow: [
      "Read the failure output and isolate the failing stage.",
      "Narrow the fix to the smallest change that restores the pipeline.",
      "Show the plan and ask before editing files that affect build behavior.",
      "Verify the pipeline or local equivalent after the fix.",
    ],
    deliverables: ["failure analysis", "fix plan", "pipeline notes", "verification command"],
    examples: [
      "Fix this failing TypeScript build in the repo",
      "Diagnose why CI is failing after the recent changes",
    ],
  },
];
